sudo: required

services:
  - docker

os: debian

dist: jessie

language: ruby
rvm:
  - 2.4.4

before_script:
  - docker-compose -f dev.yml up -d --build
  - >
    while ! docker logs noosfero | grep "Listening on tcp://0.0.0.0:3000"; do
        echo "Waiting for start script to finish...";
        sleep 5;
    done;

addons:
  postgresql: "9.4"

before_script:

env:
  matrix:
    - os=debian DIST=jessie
    - TASK=cypress:run
    - TASK=spec SPEC=spec/models
    - TASK=test:api
    - TASK=test:units
    - TASK=test:functionals
    - TASK=test:integration
    - SLICE=1/2 TASK=cucumber
    - SLICE=2/2 TASK=cucumber
    - SLICE=1/4 TASK=selenium
    - SLICE=2/4 TASK=selenium
    - SLICE=3/4 TASK=selenium
    - SLICE=4/4 TASK=selenium
    - SLICE=1/5 TASK=test:noosfero_plugins NOOSFERO_BUNDLE_OPTS=install
    - SLICE=2/5 TASK=test:noosfero_plugins NOOSFERO_BUNDLE_OPTS=install
    - SLICE=3/5 TASK=test:noosfero_plugins NOOSFERO_BUNDLE_OPTS=install
    - SLICE=4/5 TASK=test:noosfero_plugins NOOSFERO_BUNDLE_OPTS=install
    - SLICE=5/5 TASK=test:noosfero_plugins NOOSFERO_BUNDLE_OPTS=install

script:
  - docker-compose exec noosfero bundle exec rake $TASK
