version: "3"

services:
  postgres:
    image: postgres:9.4
    environment:
      POSTGRES_USER: noosfero
      POSTGRES_PASSWORD: noosfero
      POSTGRES_DB: noosfero_production
    volumes:
      - pg-prod-data:/var/lib/postgresql/data

  noosfero:
    build:
      context: .
      dockerfile: ./config/docker/prod/Dockerfile
    ports:
      - 80:3000
    depends_on:
      - postgres
    volumes:
      - ./tmp/backup:/dump
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: noosfero
      POSTGRES_PASSWORD: noosfero
      POSTGRES_DB: noosfero_production
      NOOSFERO_DUMP_FILE:

      # Set your custom credentials if you want to create a default admin account
      ADMIN_LOGIN:
      ADMIN_EMAIL:
      ADMIN_PASSWORD:

      # Set your custom environment configs
      ENVIRONMENT_NAME: Noosfero

volumes:
  pg-prod-data: {}
