version: "3.5"

services:

  postgres:
    container_name: postgres
    image: postgres:9.4
    networks:
      - noosfero-net
    env_file:
      - config/docker/prod/production.env
    volumes:
      - pg-prod-data:/var/lib/postgresql/data

  noosfero:
    container_name: noosfero
    build:
      context: .
      dockerfile: ./config/docker/prod/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - ./tmp/backup:/dump
      - static-data:/var/www/app_name/public
    networks:
      - noosfero-net
    env_file:
      - config/docker/prod/production.env 

  nginx:
    container_name: nginx    
    build:      
      context: .
      dockerfile: ./config/docker/prod/Dockerfile-nginx
    depends_on:      
      - noosfero    
    ports:      
      - 80:80
    networks:
      - noosfero-net  
    volumes:
      - static-data:/var/www/app_name/public

volumes:
  pg-prod-data: {}
  static-data:

networks:
  noosfero-net:
    name: noosfero-net
