version: 2.0

jobs:
  build:
    machine: true
    docker:
      - image: alaxalves/noosfero-ci
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-
      - save_cache:
          paths:
            - ./vendor/bundle
            - ./elasticsearch-1.7.6
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: preparing environment
          command: |
            sudo apt-get install po4a iso-codes libpq-dev libreadline-dev libxslt1-dev
            mkdir -p tmp/{pids,cache} log cache
      - run:
          name: post env preparation
          command:  |
            wget https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.4.3/elasticsearch-2.4.3.tar.gz
            tar -xvf elasticsearch-1.7.6.tar.gz
            elasticsearch-2.4.3/bin/elasticsearch: {background: true}
            script/noosfero-plugins disableall
            cp config/database.yml.circleci config/database.yml
            bundle exec rake db:schema:load
            ./script/quick-start
            bundle exec rake db:migrate

  specs-models:
    docker:
      - image: alaxalves/noosfero-ci
    steps:
      - checkout
      - run: bundle exec rake spec SPEC=spec/models

  api:
    docker:
      - image: alaxalves/noosfero-ci
    steps:
      - checkout
      - run: bundle exec rake test:api

  units:
    docker:
      - image: alaxalves/noosfero-ci
    steps:
      - checkout
      - run: bundle exec rake test:api

  functionals:
    docker:
      - image: alaxalves/noosfero-ci
    steps:
      - checkout
      - run: bundle exec rake test:functionals

  integration:
    docker:
      - image: alaxalves/noosfero-ci
    steps:
      - checkout
      - run: bundle exec rake test:integration

  cucumber-1:
    docker:
      - image: alaxalves/noosfero-ci
    steps:
      - checkout
      - run: SLICE=1/2 bundle exec rake cucumber

  cucumber-2:
    docker:
      - image: alaxalves/noosfero-ci
    steps:
      - checkout
      - run: SLICE=2/2 bundle exec rake cucumber

  selenium-1:
    docker:
      - image: alaxalves/noosfero-ci
    steps:
      - checkout
      - run: SLICE=1/6 bundle exec rake selenium

  selenium-2:
    docker:
      - image: alaxalves/noosfero-ci
    steps:
      - checkout
      - run: SLICE=2/6 bundle exec rake selenium

  selenium-3:
    docker:
      - image: alaxalves/noosfero-ci
    steps:
      - checkout
      - run: SLICE=3/6 bundle exec rake selenium
  
  selenium-4:
    docker:
      - image: alaxalves/noosfero-ci
    steps:
      - checkout
      - run: SLICE=4/6 bundle exec rake selenium
  
  selenium-5:
    docker:
      - image: alaxalves/noosfero-ci
    steps:
      - checkout
      - run: SLICE=5/6 bundle exec rake selenium

  selenium-6:
    docker:
      - image: alaxalves/noosfero-ci
    steps:
      - checkout
      - run: SLICE=6/6 bundle exec rake selenium

  plugins-1:
    docker:
      - image: alaxalves/noosfero-ci
    steps:
      - checkout
      - run: SLICE=1/5 bundle exec rake test:noosfero_plugins NOOSFERO_BUNDLE_OPTS=install

  plugins-2:
    docker:
      - image: alaxalves/noosfero-ci

    steps:
      - checkout
      - run: SLICE=2/5 bundle exec rake test:noosfero_plugins NOOSFERO_BUNDLE_OPTS=install

  plugins-3:
    docker:
      - image: alaxalves/noosfero-ci
    steps:
      - checkout
      - run: SLICE=3/5 bundle exec rake test:noosfero_plugins NOOSFERO_BUNDLE_OPTS=install

  plugins-4:
    docker:
      - image: alaxalves/noosfero-ci
    steps:
      - checkout
      - run: SLICE=4/5 bundle exec rake test:noosfero_plugins NOOSFERO_BUNDLE_OPTS=install

  plugins-5:
    docker:
      - image: alaxalves/noosfero-ci
    steps:
      - checkout
      - run: SLICE=5/5 bundle exec rake test:noosfero_plugins NOOSFERO_BUNDLE_OPTS=install

workflows:
  version: 2.0
  noosfero:
    jobs:
      - build
      - specs-models:
          requires:
           - build
      - api:
          requires:
           - build
      - units:
          requires:
           - build
      - functionals:
          requires:
           - build
      - integration:
          requires:
           - build
      - cucumber-1:
          requires:
           - build
      - cucumber-2:
          requires:
           - build
      - selenium-1:
          requires:
           - build
      - selenium-2:
          requires:
           - build
      - selenium-3:
          requires:
           - build
      - selenium-4:
          requires:
           - build
      - selenium-5:
          requires:
           - build
      - selenium-6:
          requires:
           - build
      - plugins-1:
          requires:
           - build
      - plugins-2:
          requires:
           - build
      - plugins-3:
          requires:
           - build
      - plugins-4:
          requires:
           - build
      - plugins-5:
          requires:
           - build
